spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springboot:
  jwt:
    secret: ${JWT_SECRET_KEY}

webclient:
  searchUrl: ${SEARCH_URL}
  statusUrlStart: ${STATUS_URL_START}
  statusUrlEnd: ${STATUS_URL_END}
  libSearchUrl: ${LIB_SEARCH_URL}

